server:
 port: 9400
 servlet:
   context-path: /adApi

multipart:
 maxFileSize: 1024Mb
 maxRequestSize: 1024Mb

image:
 path: //data//app//uploadfiles//

prefix:
 url: http://192.168.46.138:9004/uploadfiles/
