server:
 port: 9400
 servlet:
   context-path: /adApi

spring:
 servlet:
   multipart:
    maxFileSize: 100MB
    maxRequestSize: 100MB

image:
 path: //data//app//uploadfiles//

prefix:
 url: http://192.168.46.138:9004/uploadfiles/
